/*******************************************************************************
 * Copyright (c) 2022, 2023 Martin Pernollet & contributors.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.08 at 06:58:36 PM CET 
//


package jextract.gl.xml.parser;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jextractgl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RegistryExtensionsExtensionRequire_QNAME = new QName("", "require");
    private final static QName _RegistryTypesTypeApientry_QNAME = new QName("", "apientry");
    private final static QName _RegistryTypesTypeName_QNAME = new QName("", "name");
    private final static QName _RegistryExtensionsExtensionRequireType_QNAME = new QName("", "type");
    private final static QName _RegistryExtensionsExtensionRequireCommand_QNAME = new QName("", "command");
    private final static QName _RegistryExtensionsExtensionRequireEnum_QNAME = new QName("", "enum");
    private final static QName _RegistryEnumsUnused_QNAME = new QName("", "unused");
    private final static QName _RegistryCommandsCommandParamPtype_QNAME = new QName("", "ptype");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jextractgl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Registry.Extensions.Extension }
     * 
     */
    public Registry.Extensions.Extension createRegistryExtensionsExtension() {
        return new Registry.Extensions.Extension();
    }

    /**
     * Create an instance of {@link Registry.Feature.Remove }
     * 
     */
    public Registry.Feature.Remove createRegistryFeatureRemove() {
        return new Registry.Feature.Remove();
    }

    /**
     * Create an instance of {@link Registry.Commands.Command.Param }
     * 
     */
    public Registry.Commands.Command.Param createRegistryCommandsCommandParam() {
        return new Registry.Commands.Command.Param();
    }

    /**
     * Create an instance of {@link Registry.Feature.Require.Type }
     * 
     */
    public Registry.Feature.Require.Type createRegistryFeatureRequireType() {
        return new Registry.Feature.Require.Type();
    }

    /**
     * Create an instance of {@link Registry.Enums.Unused }
     * 
     */
    public Registry.Enums.Unused createRegistryEnumsUnused() {
        return new Registry.Enums.Unused();
    }

    /**
     * Create an instance of {@link Registry.Feature }
     * 
     */
    public Registry.Feature createRegistryFeature() {
        return new Registry.Feature();
    }

    /**
     * Create an instance of {@link Registry.Commands }
     * 
     */
    public Registry.Commands createRegistryCommands() {
        return new Registry.Commands();
    }

    /**
     * Create an instance of {@link Registry.Extensions.Extension.Require.Command }
     * 
     */
    public Registry.Extensions.Extension.Require.Command createRegistryExtensionsExtensionRequireCommand() {
        return new Registry.Extensions.Extension.Require.Command();
    }

    /**
     * Create an instance of {@link Registry.Feature.Require.Enum }
     * 
     */
    public Registry.Feature.Require.Enum createRegistryFeatureRequireEnum() {
        return new Registry.Feature.Require.Enum();
    }

    /**
     * Create an instance of {@link Registry.Commands.Command.Vecequiv }
     * 
     */
    public Registry.Commands.Command.Vecequiv createRegistryCommandsCommandVecequiv() {
        return new Registry.Commands.Command.Vecequiv();
    }

    /**
     * Create an instance of {@link Registry }
     * 
     */
    public Registry createRegistry() {
        return new Registry();
    }

    /**
     * Create an instance of {@link Registry.Commands.Command.Proto }
     * 
     */
    public Registry.Commands.Command.Proto createRegistryCommandsCommandProto() {
        return new Registry.Commands.Command.Proto();
    }

    /**
     * Create an instance of {@link Registry.Feature.Require }
     * 
     */
    public Registry.Feature.Require createRegistryFeatureRequire() {
        return new Registry.Feature.Require();
    }

    /**
     * Create an instance of {@link Registry.Commands.Command.Alias }
     * 
     */
    public Registry.Commands.Command.Alias createRegistryCommandsCommandAlias() {
        return new Registry.Commands.Command.Alias();
    }

    /**
     * Create an instance of {@link Registry.Types }
     * 
     */
    public Registry.Types createRegistryTypes() {
        return new Registry.Types();
    }

    /**
     * Create an instance of {@link Registry.Extensions.Extension.Require.Type }
     * 
     */
    public Registry.Extensions.Extension.Require.Type createRegistryExtensionsExtensionRequireType() {
        return new Registry.Extensions.Extension.Require.Type();
    }

    /**
     * Create an instance of {@link Registry.Types.Type }
     * 
     */
    public Registry.Types.Type createRegistryTypesType() {
        return new Registry.Types.Type();
    }

    /**
     * Create an instance of {@link Registry.Extensions.Extension.Require }
     * 
     */
    public Registry.Extensions.Extension.Require createRegistryExtensionsExtensionRequire() {
        return new Registry.Extensions.Extension.Require();
    }

    /**
     * Create an instance of {@link Registry.Enums }
     * 
     */
    public Registry.Enums createRegistryEnums() {
        return new Registry.Enums();
    }

    /**
     * Create an instance of {@link Registry.Feature.Remove.Command }
     * 
     */
    public Registry.Feature.Remove.Command createRegistryFeatureRemoveCommand() {
        return new Registry.Feature.Remove.Command();
    }

    /**
     * Create an instance of {@link Registry.Commands.Command.Glx }
     * 
     */
    public Registry.Commands.Command.Glx createRegistryCommandsCommandGlx() {
        return new Registry.Commands.Command.Glx();
    }

    /**
     * Create an instance of {@link Registry.Extensions }
     * 
     */
    public Registry.Extensions createRegistryExtensions() {
        return new Registry.Extensions();
    }

    /**
     * Create an instance of {@link Registry.Commands.Command }
     * 
     */
    public Registry.Commands.Command createRegistryCommandsCommand() {
        return new Registry.Commands.Command();
    }

    /**
     * Create an instance of {@link Registry.Feature.Require.Command }
     * 
     */
    public Registry.Feature.Require.Command createRegistryFeatureRequireCommand() {
        return new Registry.Feature.Require.Command();
    }

    /**
     * Create an instance of {@link Registry.Extensions.Extension.Require.Enum }
     * 
     */
    public Registry.Extensions.Extension.Require.Enum createRegistryExtensionsExtensionRequireEnum() {
        return new Registry.Extensions.Extension.Require.Enum();
    }

    /**
     * Create an instance of {@link Registry.Enums.Enum }
     * 
     */
    public Registry.Enums.Enum createRegistryEnumsEnum() {
        return new Registry.Enums.Enum();
    }

    /**
     * Create an instance of {@link Registry.Feature.Remove.Enum }
     * 
     */
    public Registry.Feature.Remove.Enum createRegistryFeatureRemoveEnum() {
        return new Registry.Feature.Remove.Enum();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Registry.Extensions.Extension.Require }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "require", scope = Registry.Extensions.Extension.class)
    public JAXBElement<Registry.Extensions.Extension.Require> createRegistryExtensionsExtensionRequire(Registry.Extensions.Extension.Require value) {
        return new JAXBElement<Registry.Extensions.Extension.Require>(_RegistryExtensionsExtensionRequire_QNAME, Registry.Extensions.Extension.Require.class, Registry.Extensions.Extension.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "apientry", scope = Registry.Types.Type.class)
    public JAXBElement<String> createRegistryTypesTypeApientry(String value) {
        return new JAXBElement<String>(_RegistryTypesTypeApientry_QNAME, String.class, Registry.Types.Type.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name", scope = Registry.Types.Type.class)
    public JAXBElement<String> createRegistryTypesTypeName(String value) {
        return new JAXBElement<String>(_RegistryTypesTypeName_QNAME, String.class, Registry.Types.Type.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Registry.Extensions.Extension.Require.Type }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "type", scope = Registry.Extensions.Extension.Require.class)
    public JAXBElement<Registry.Extensions.Extension.Require.Type> createRegistryExtensionsExtensionRequireType(Registry.Extensions.Extension.Require.Type value) {
        return new JAXBElement<Registry.Extensions.Extension.Require.Type>(_RegistryExtensionsExtensionRequireType_QNAME, Registry.Extensions.Extension.Require.Type.class, Registry.Extensions.Extension.Require.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Registry.Extensions.Extension.Require.Command }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "command", scope = Registry.Extensions.Extension.Require.class)
    public JAXBElement<Registry.Extensions.Extension.Require.Command> createRegistryExtensionsExtensionRequireCommand(Registry.Extensions.Extension.Require.Command value) {
        return new JAXBElement<Registry.Extensions.Extension.Require.Command>(_RegistryExtensionsExtensionRequireCommand_QNAME, Registry.Extensions.Extension.Require.Command.class, Registry.Extensions.Extension.Require.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Registry.Extensions.Extension.Require.Enum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "enum", scope = Registry.Extensions.Extension.Require.class)
    public JAXBElement<Registry.Extensions.Extension.Require.Enum> createRegistryExtensionsExtensionRequireEnum(Registry.Extensions.Extension.Require.Enum value) {
        return new JAXBElement<Registry.Extensions.Extension.Require.Enum>(_RegistryExtensionsExtensionRequireEnum_QNAME, Registry.Extensions.Extension.Require.Enum.class, Registry.Extensions.Extension.Require.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Registry.Enums.Unused }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "unused", scope = Registry.Enums.class)
    public JAXBElement<Registry.Enums.Unused> createRegistryEnumsUnused(Registry.Enums.Unused value) {
        return new JAXBElement<Registry.Enums.Unused>(_RegistryEnumsUnused_QNAME, Registry.Enums.Unused.class, Registry.Enums.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Registry.Enums.Enum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "enum", scope = Registry.Enums.class)
    public JAXBElement<Registry.Enums.Enum> createRegistryEnumsEnum(Registry.Enums.Enum value) {
        return new JAXBElement<Registry.Enums.Enum>(_RegistryExtensionsExtensionRequireEnum_QNAME, Registry.Enums.Enum.class, Registry.Enums.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Registry.Feature.Require.Type }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "type", scope = Registry.Feature.Require.class)
    public JAXBElement<Registry.Feature.Require.Type> createRegistryFeatureRequireType(Registry.Feature.Require.Type value) {
        return new JAXBElement<Registry.Feature.Require.Type>(_RegistryExtensionsExtensionRequireType_QNAME, Registry.Feature.Require.Type.class, Registry.Feature.Require.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Registry.Feature.Require.Enum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "enum", scope = Registry.Feature.Require.class)
    public JAXBElement<Registry.Feature.Require.Enum> createRegistryFeatureRequireEnum(Registry.Feature.Require.Enum value) {
        return new JAXBElement<Registry.Feature.Require.Enum>(_RegistryExtensionsExtensionRequireEnum_QNAME, Registry.Feature.Require.Enum.class, Registry.Feature.Require.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Registry.Feature.Require.Command }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "command", scope = Registry.Feature.Require.class)
    public JAXBElement<Registry.Feature.Require.Command> createRegistryFeatureRequireCommand(Registry.Feature.Require.Command value) {
        return new JAXBElement<Registry.Feature.Require.Command>(_RegistryExtensionsExtensionRequireCommand_QNAME, Registry.Feature.Require.Command.class, Registry.Feature.Require.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name", scope = Registry.Commands.Command.Param.class)
    public JAXBElement<String> createRegistryCommandsCommandParamName(String value) {
        return new JAXBElement<String>(_RegistryTypesTypeName_QNAME, String.class, Registry.Commands.Command.Param.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ptype", scope = Registry.Commands.Command.Param.class)
    public JAXBElement<String> createRegistryCommandsCommandParamPtype(String value) {
        return new JAXBElement<String>(_RegistryCommandsCommandParamPtype_QNAME, String.class, Registry.Commands.Command.Param.class, value);
    }

}
