/*******************************************************************************
 * Copyright (c) 2022, 2023 Martin Pernollet & contributors.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA
 *******************************************************************************/
package panamagl.factory;

import java.io.IOException;
import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.util.ArrayList;
import java.util.List;
import panamagl.GLCanvas;
import panamagl.GLEventListener;
import panamagl.canvas.GLCanvasFactory;
import panamagl.offscreen.FBO;
import panamagl.offscreen.OffscreenRenderer;
import panamagl.opengl.GL;
import panamagl.opengl.GLContext;
import panamagl.platform.Platform;
import panamagl.platform.PlatformMatcher;
import panamagl.utils.ClassloaderUtils;

/**
 * A {@link PanamaGLFactory} generates components for a given platform (CPU, OS) and
 * will ensure the appropriate bindings as well as OpenGL way of implementing a 
 * rendering technic are applied a target platform.
 * 
 * Platforms are resolved automatically through {@link PanamaGLFactory.select()} which 
 * picks the first {@link PanamaGLFactory} in classpath that {@link #matches(Platform)}
 * hence the executing computer.
 * 
 * PanamaGL component initialization starts while initializing a new {@link GLCanvas}
 * for adding to an existing UI. The canvas will initialize all subsequent required 
 * components in order and will only require a {@link GLEventListener} to perform the
 * application OpenGL calls through the {@link GL} interface.
 * 
 * 
 * The initialization hence looks like :
 * <pre>
 * <code>
 * GLEventAdapter listener = TeapotGLEventListener();
 * PanamaGLFactory factory = PanamaGLFactory.select();
 * GLCanvasSwing panel = factory.newCanvasSwing();
 * panel.setGLEventListener(listener);
 * frame.add(panel);
 * </code>
 * </pre>
 * 
 * Classes generated by the available factories are represented below :
 * 
 * <img src="doc-files/factory.png"/>
 * 
 * @author Martin Pernollet
 *
 */
public interface PanamaGLFactory extends PlatformMatcher{

  GL newGL();
  GLContext newGLContext();
  FBO newFBO(int width, int height);
  OffscreenRenderer newOffscreenRenderer();

  void destroyContext();
  
  /////////////////////////////////////////////////////
  //
  // Factory auto select
  //
  /////////////////////////////////////////////////////
  
  /** Returns the first factory that is is compatible with the current {@link Platform}.*/
  public static PanamaGLFactory select() {

    Platform os = new Platform();

    return selectFor(os);
  }
  
  public static PanamaGLFactory selectFor(Platform os) {
    List<PanamaGLFactory> factories = findFactories();
    
    for(PanamaGLFactory factory : factories) {
      if(factory.matches(os)) {
        return factory;
      }
    }
    return null;
  }
  
  public static List<PanamaGLFactory> findFactories() {
    Class<?> exclude = APanamaGLFactory.class;
    Class<?> implem = PanamaGLFactory.class;
    String packge = "panamagl";

    return findFactories(exclude, implem, packge);
  }
  
  public static List<PanamaGLFactory> findFactories(Class<?> exclude, Class<?> implem, String packge) {
    List<PanamaGLFactory> factories = new ArrayList<>();

    try {
      
      for (Class<?> c : ClassloaderUtils.findFactoryClasses(packge, implem, exclude)) {
        try {
          // Find the default constructor
          Constructor<?> cons = findConstructor(c);

          // Init the factory
          PanamaGLFactory f = (PanamaGLFactory)cons.newInstance();
          factories.add(f);
          
        } catch (IllegalArgumentException e) {
          e.printStackTrace();
        } catch (InvocationTargetException e) {
          e.printStackTrace();
        } catch (SecurityException e) {
          e.printStackTrace();
        } catch (InstantiationException e) {
          e.printStackTrace();
        } catch (IllegalAccessException e) {
          e.printStackTrace();
        }
      }
    } catch (ClassNotFoundException e) {
      e.printStackTrace();
    } catch (IOException e) {
      e.printStackTrace();
    }
    
    return factories;
  }
  
  public static Constructor<?> findConstructor(Class<?> c) {
    Constructor<?> cons = null;
    for(Constructor<?>  co: c.getConstructors()) {
      if(co.getParameterCount()==0) {
        cons = co;
      }
    }
    if(cons==null) {
      throw new RuntimeException("No factory constructor with 0 argument for " + c.getName());
    }
    return cons;
  }

}
