package panamagl.platform.linux.arm;

import panamagl.platform.linux.x64.GL_linux_x64;

/**
 * {@link panamagl.opengl.GL} for Linux on ARM64.
 * 
 * Linux on ARM64 has the same data model (LP64) and the same structure layouts as Linux on x64 for
 * the OpenGL, GLU, GLUT and GLX APIs, and the Foreign Function and Memory API applies the ARM64
 * calling convention at runtime. The bindings generated by jextract for Linux x64 can hence be used
 * as is, provided that the ARM64 builds of libGL, libGLU and libglut are in the java.library.path
 * (e.g. /usr/lib/aarch64-linux-gnu).
 */
public class GL_linux_arm extends GL_linux_x64 {
  public GL_linux_arm() {
    super();
  }
}
