package panamagl.platform.windows.arm;

import panamagl.platform.windows.x64.GL_windows_x64;

/**
 * {@link panamagl.opengl.GL} for Windows on ARM64.
 * 
 * Windows on ARM64 has the same data model (LLP64) and the same structure layouts as Windows on
 * x64, and the Foreign Function and Memory API applies the ARM64 calling convention at runtime.
 * The bindings generated by jextract for Windows x64 can hence be used as is, provided that the
 * ARM64 builds of opengl32.dll and freeglut.dll are in the java.library.path.
 */
public class GL_windows_arm extends GL_windows_x64 {
  public GL_windows_arm() {
    super();
  }
}
